import { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';

import { DisclaimerBanner } from '@/components/disclaimer-banner';
import { ServerRecommendations } from '@/components/server-recommendations';
import { ApiError, type RiskLevel } from '@/lib/api';
import { getChildRecommendations, type RecommendationResult, type ServerChild } from '@/lib/children-api';
import { ageGroup, ageGroupLabel, childDisplayName, getSelectedChild } from '@/lib/current-child';
import { trackEvent } from '@/lib/engagement-api';
import { resolveStartRoute, routeForGateError } from '@/lib/gate';
import { getCurrentCoords } from '@/lib/location';
import { enableLocalNotifications, maybeNotifyRiskTransition } from '@/lib/notifications';
import { aqiColour, aqiLevel, riskBg, riskRing, riskText } from '@/lib/risk';

export default function HomeScreen() {
  const [child, setChild] = useState<ServerChild | null>(null);
  const [result, setResult] = useState<RecommendationResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [updatedAt, setUpdatedAt] = useState<string | null>(null);
  const [gateChecked, setGateChecked] = useState(false);

  const loadRisk = useCallback(async (target?: ServerChild | null) => {
    setLoading(true);
    setError(null);

    try {
      const selected = target ?? (await getSelectedChild());
      setChild(selected);

      if (!selected) {
        router.replace('/profile-setup');
        return;
      }

      const { lat, lon } = await getCurrentCoords();
      const data = await getChildRecommendations(selected.id, lat, lon);

      setResult(data);
      setUpdatedAt(new Date().toISOString());

      // Local, offline alert if risk crossed into/out of HIGH (no server push).
      maybeNotifyRiskTransition(data.overall_risk, data.priority_actions?.[0]);

      // Engagement: a successful risk check (server auto-logs add_child; not here).
      trackEvent('risk_check', { priority: data.overall_risk, child_id: selected.id });
    } catch (err) {
      if (routeForGateError(err)) return;
      setError(err instanceof ApiError ? err.message : 'Unable to check risk right now. Please try again.');
    } finally {
      setLoading(false);
    }
  }, []);

  // On mount, walk the server gates and land here only when fully onboarded.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const route = await resolveStartRoute();
        if (cancelled) return;
        if (route !== '/') {
          router.replace(route);
          return;
        }
        setGateChecked(true);
        // Fully local notifications: permission + channel + daily reminder. No push.
        enableLocalNotifications().catch(() => {});
        loadRisk();
      } catch {
        if (!cancelled) {
          setGateChecked(true);
          setLoading(false);
          setError('Unable to reach the server. Please check your connection and try again.');
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [loadRisk]);

  // When the selected child changes elsewhere (hub), refresh on focus.
  useFocusEffect(
    useCallback(() => {
      if (!gateChecked) return;
      let active = true;
      (async () => {
        const selected = await getSelectedChild();
        if (!active) return;
        if (selected?.id !== child?.id) loadRisk(selected);
      })();
      return () => {
        active = false;
      };
    }, [gateChecked, child?.id, loadRisk])
  );

  const shareAlert = async () => {
    if (!result) return;
    const env = result.environment ?? {};
    const message = `Child Health Alert

Risk Priority: ${result.overall_risk?.toUpperCase() ?? 'UNKNOWN'}
Primary hazards: ${result.primary_hazards?.join(', ') || 'none'}

Priority actions:
${(result.priority_actions ?? []).map((a) => `• ${a}`).join('\n')}

Environmental conditions:
Temperature: ${env.temperature ?? '—'}°C
AQI (US): ${env.aqi ?? 'Unavailable'}

${result.disclaimer ?? 'Generated by Child Guard. Environmental guidance only — not medical advice.'}`;
    const outcome = await Share.share({ message });
    if (outcome.action === Share.sharedAction) {
      trackEvent('share_summary', { priority: result.overall_risk, child_id: child?.id ?? null });
    }
  };

  const formatUpdated = (iso: string | null) => {
    if (!iso) return 'Not yet';
    return new Date(iso).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  if (!gateChecked || (loading && !result)) {
    return (
      <View style={[styles.safe, styles.center]}>
        <ActivityIndicator size="large" />
        <Text style={styles.loadingText}>Assessing environmental risk…</Text>
      </View>
    );
  }

  const env = result?.environment ?? {};
  const risks = result?.risks ?? {};
  const elevated = Object.values(risks).filter((v) => v === 'high' || v === 'moderate').length;
  const total = Object.values(risks).length || 4;

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}>
      <ScrollView style={styles.screen} contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <View style={styles.headerTopRow}>
            <View style={styles.liveRow}>
              <View style={styles.liveDot} />
              <Text style={styles.liveText}>LIVE MONITORING</Text>
            </View>
            <Pressable style={styles.settingsButton} onPress={() => router.push('/settings')} hitSlop={8} accessibilityLabel="Settings">
              <Ionicons name="settings-outline" size={22} color="#334155" />
            </Pressable>
          </View>

          <Text style={styles.title}>Environmental{'\n'}Intelligence</Text>
          <Text style={styles.subtitle}>Real-time environmental risk monitoring for children&apos;s health and safety.</Text>
        </View>

        <DisclaimerBanner style={styles.disclaimer} />

        {/* Status strip */}
        <View style={styles.statusStrip}>
          <View style={styles.statusItem}>
            <View style={styles.statusIcon}>
              <MaterialCommunityIcons name="weather-hazy" size={22} color="#2F6BFF" />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.statusMain}>AQI {env.aqi ?? '--'}</Text>
              <Text style={[styles.aqiText, { color: aqiColour(env.aqi) }]}>{aqiLevel(env.aqi).toUpperCase()}</Text>
            </View>
          </View>
          <View style={styles.statusDivider} />
          <View style={styles.statusItem}>
            <View style={styles.statusIcon}>
              <Ionicons name="sync-outline" size={22} color="#2F6BFF" />
            </View>
            <View>
              <Text style={styles.statusMain}>{loading ? 'Checking' : 'Live'}</Text>
              <Text style={styles.statusSub}>{formatUpdated(updatedAt)}</Text>
            </View>
          </View>
        </View>

        {/* Child switcher card */}
        {child && (
          <Pressable style={styles.childCard} onPress={() => router.push('/children')} accessibilityLabel="Switch or manage children">
            <View style={styles.avatarCircle}>
              <Ionicons name="person" size={30} color="#2F6B9A" />
            </View>
            <View style={styles.childInfo}>
              <Text style={styles.childName} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.75}>
                {childDisplayName(child)}
              </Text>
              <Text style={styles.childAge} numberOfLines={1}>
                {child.age} {child.age === 1 ? 'year' : 'years'} · {ageGroupLabel(ageGroup(child.age))}
              </Text>
              <View style={styles.switchHintRow}>
                <Ionicons name="swap-horizontal" size={13} color="#2F6BFF" />
                <Text style={styles.switchHint}>Tap to switch or add children</Text>
              </View>
            </View>
            <Pressable style={styles.editButton} onPress={() => router.push(`/child-form?childId=${child.id}`)} accessibilityLabel="Edit child">
              <Ionicons name="create-outline" size={18} color="#2F6BFF" />
              <Text style={styles.editText}>Edit</Text>
            </Pressable>
          </Pressable>
        )}

        <Pressable style={styles.checkButton} onPress={() => loadRisk()}>
          <Text style={styles.checkButtonText}>{loading ? 'Checking…' : 'Check Current Risk'}</Text>
        </Pressable>

        {error && (
          <View style={styles.errorBanner}>
            <Ionicons name="warning-outline" size={20} color="#B91C1C" />
            <Text style={styles.errorText}>{error}</Text>
          </View>
        )}

        {result && (
          <View style={styles.section}>
            <View style={[styles.riskHero, { backgroundColor: riskBg(result.overall_risk) }]}>
              <View style={{ flex: 1 }}>
                <Text style={styles.riskLabel}>Environmental Risk</Text>
                <Text style={[styles.riskLevel, { color: riskText(result.overall_risk) }]}>
                  {result.overall_risk?.toUpperCase() ?? 'UNKNOWN'}
                </Text>
                <Text style={styles.riskDescription}>
                  {result.primary_hazards?.length ? `Primary: ${result.primary_hazards.join(', ')}` : 'No major hazards detected.'}
                </Text>
              </View>
              <View style={[styles.riskRing, { borderColor: riskRing(result.overall_risk).border, backgroundColor: riskRing(result.overall_risk).fill }]}>
                <Text style={[styles.riskNumber, { color: riskText(result.overall_risk) }]}>
                  {elevated}
                  <Text style={styles.riskOutOf}>/{total}</Text>
                </Text>
                <Text style={styles.riskOutOf}>elevated</Text>
              </View>
            </View>

            <View style={styles.domainRow}>
              <RiskCard title="Heat Stress" value={risks.heat_stress} icon="thermometer" />
              <RiskCard title="Respiratory" value={risks.respiratory} icon="lungs" />
              <RiskCard title="Dengue" value={risks.dengue} icon="bug-outline" />
            </View>

            <View style={styles.dataCard}>
              <View style={styles.cardHeader}>
                <Text style={styles.cardTitle}>Live Environmental Data</Text>
                <Pressable onPress={() => router.push('/map')}>
                  <Text style={styles.mapLink}>View on Map ›</Text>
                </Pressable>
              </View>
              <View style={styles.metricRow}>
                <Metric icon="thermometer" value={`${env.temperature ?? '—'}°C`} label="Temperature" />
                <Metric icon="water-outline" value={`${env.humidity ?? '—'}%`} label="Humidity" />
                <Metric icon="rainy-outline" value={`${env.rainfall ?? '—'} mm`} label="Rainfall" />
                <Metric icon="ellipse-outline" value={`${env.pm2_5 ?? '—'}`} label="PM2.5" />
              </View>
            </View>

            <View style={styles.actionCard}>
              <Text style={styles.cardTitle}>Personalised Recommendations</Text>
              <Text style={styles.actionSubtitle}>
                Tailored to {childDisplayName(child ?? ({ name: 'your child' } as ServerChild))}&apos;s profile and today&apos;s conditions
              </Text>
              <ServerRecommendations result={result} />
            </View>

            <Pressable style={styles.shareButton} onPress={shareAlert}>
              <View style={styles.shareIcon}>
                <Ionicons name="paper-plane-outline" size={22} color="#FFFFFF" />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={styles.shareTitle}>Share Alert Summary</Text>
                <Text style={styles.shareSub}>Send this report to caregivers or health professionals</Text>
              </View>
              <Ionicons name="chevron-forward" size={24} color="#FFFFFF" />
            </Pressable>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function RiskCard({ title, value, icon }: { title: string; value?: string; icon: any }) {
  const level = (value === 'high' || value === 'moderate' ? value : 'low') as RiskLevel;
  const colour = riskText(level);
  return (
    <View style={styles.riskCard}>
      <View style={[styles.domainIcon, { backgroundColor: riskBg(level) }]}>
        <MaterialCommunityIcons name={icon} size={25} color={colour} />
      </View>
      <Text style={styles.riskTitle}>{title}</Text>
      <Text style={[styles.riskValue, { color: colour }]}>{value?.toUpperCase() ?? 'UNKNOWN'}</Text>
      <Text style={styles.domainScore}>Risk domain</Text>
      <View style={[styles.sparkLine, { backgroundColor: colour }]} />
    </View>
  );
}

function Metric({ icon, value, label }: { icon: any; value: string; label: string }) {
  return (
    <View style={styles.metricCard}>
      <Ionicons name={icon} size={21} color="#2F6B9A" />
      <Text style={styles.metricValue}>{value}</Text>
      <Text style={styles.metricLabel}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F5F8FC' },
  center: { alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: '#4B5563', fontSize: 15 },
  screen: { flex: 1, backgroundColor: '#F5F8FC' },
  container: { paddingHorizontal: 24, paddingTop: 20, paddingBottom: 130 },
  header: { marginBottom: 16 },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  liveRow: { flexDirection: 'row', alignItems: 'center' },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#36D399', marginRight: 8 },
  liveText: { color: '#245DCC', fontSize: 13, fontWeight: '900', letterSpacing: 0.5 },
  settingsButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E5EAF2' },
  title: { color: '#101828', fontSize: 42, lineHeight: 46, fontWeight: '900', letterSpacing: -1.3, marginTop: 14 },
  subtitle: { color: '#667085', fontSize: 16, lineHeight: 24, marginTop: 16, maxWidth: 310 },
  disclaimer: { marginBottom: 18 },
  statusStrip: { backgroundColor: '#FFFFFF', borderRadius: 22, paddingVertical: 16, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E6EBF2', marginBottom: 18 },
  statusItem: { flex: 1, justifyContent: 'center', flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F0F5FF', alignItems: 'center', justifyContent: 'center' },
  statusDivider: { width: 1, height: 40, backgroundColor: '#D7DEE8', marginHorizontal: 8 },
  statusMain: { color: '#101828', fontSize: 13, fontWeight: '900' },
  statusSub: { color: '#7A8496', fontSize: 12, marginTop: 2 },
  aqiText: { fontSize: 12, fontWeight: '800', marginTop: 2 },
  errorBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FEE2E2', borderRadius: 16, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: '#FCA5A5' },
  errorText: { flex: 1, color: '#B91C1C', fontSize: 13, fontWeight: '700', lineHeight: 18 },
  childCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 20, flexDirection: 'row', alignItems: 'center', gap: 16, borderWidth: 1, borderColor: '#E6EBF2', marginBottom: 18 },
  avatarCircle: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#DCEEFF', alignItems: 'center', justifyContent: 'center' },
  childInfo: { flex: 1, minWidth: 0 },
  childName: { color: '#101828', fontSize: 20, lineHeight: 24, fontWeight: '900' },
  childAge: { color: '#667085', fontSize: 13, fontWeight: '700', marginTop: 1 },
  switchHintRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 6 },
  switchHint: { color: '#2F6BFF', fontSize: 12, fontWeight: '700' },
  editButton: { backgroundColor: '#EEF5FF', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  editText: { color: '#2F6BFF', fontSize: 13, fontWeight: '900' },
  checkButton: { backgroundColor: '#101828', borderRadius: 22, paddingVertical: 18, marginBottom: 20 },
  checkButtonText: { color: '#FFFFFF', textAlign: 'center', fontSize: 17, fontWeight: '900' },
  section: { gap: 16 },
  riskHero: { borderRadius: 24, padding: 22, flexDirection: 'row', alignItems: 'center' },
  riskLabel: { color: '#667085', fontSize: 15, fontWeight: '900' },
  riskLevel: { fontSize: 34, fontWeight: '900', marginTop: 8 },
  riskDescription: { color: '#667085', fontSize: 14, lineHeight: 20, marginTop: 6, maxWidth: 210 },
  riskRing: { width: 96, height: 96, borderRadius: 48, borderWidth: 10, alignItems: 'center', justifyContent: 'center' },
  riskNumber: { fontSize: 32, fontWeight: '900' },
  riskOutOf: { color: '#667085', fontSize: 13, fontWeight: '800' },
  domainRow: { flexDirection: 'row', gap: 10 },
  riskCard: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 18, padding: 13, borderWidth: 1, borderColor: '#E6EBF2' },
  domainIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  riskTitle: { color: '#101828', fontSize: 13, fontWeight: '900' },
  riskValue: { fontSize: 18, fontWeight: '900', marginTop: 2 },
  domainScore: { color: '#667085', fontSize: 11, marginTop: 3 },
  sparkLine: { height: 3, borderRadius: 3, opacity: 0.55, marginTop: 10 },
  dataCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 18, borderWidth: 1, borderColor: '#E6EBF2' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  cardTitle: { color: '#101828', fontSize: 17, fontWeight: '900', marginBottom: 4 },
  mapLink: { color: '#2F6BFF', fontSize: 14, fontWeight: '800' },
  metricRow: { flexDirection: 'row', gap: 10 },
  metricCard: { flex: 1, backgroundColor: '#F8FAFC', borderRadius: 16, padding: 12, borderWidth: 1, borderColor: '#E6EBF2' },
  metricValue: { color: '#101828', fontSize: 15, fontWeight: '900', marginTop: 8 },
  metricLabel: { color: '#667085', fontSize: 10, marginTop: 6 },
  actionCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 18, borderWidth: 1, borderColor: '#E6EBF2' },
  actionSubtitle: { color: '#667085', fontSize: 13, lineHeight: 19, marginTop: 2, marginBottom: 14 },
  shareButton: { backgroundColor: '#2F55E7', borderRadius: 22, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 },
  shareIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' },
  shareTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '900' },
  shareSub: { color: '#DDE6FF', fontSize: 12, marginTop: 3 },
});
